const programasListado = [
    {
        id:1,
        programa: 'Inglés',
        pais:'Australia',
        descripcion:'Desde un mes de 20 a 30 horas a la semana + Programa (ejemplo de programa de seis meses).',
        ingreso:'Enero/Diciembre',
        perfil: 'Curso de Inglés para mayores de 18 años.',
        beca:'Seguro incluido.',
        precio:'$6,000 AUD',
        nivelIngles:'No aplica',
        razones:'Contiene una llamativa arquitectura, sus imponentes edificios y sus numerosas instalaciones de ocio, están situados en la costa oeste o sur, ofreciendo así amplias playas y un clima más fresco que en el interior. Un buen lugar para aprender y descansar.',
        imagen: `url(${'../Imagenes/students5.jpg'})`
    },
    {
        id:2,
        programa: 'Inglés',
        pais:'Canadá',
        descripcion:'Desde un mes de 20 a 30 hrs a la semana + Programa (ejemplo de programa de seis meses), modalidad online y presencial.',
        ingreso:'2021 - 2022',
        perfil: 'Inglés presencial. Persona que quiera mejorar su nivel de inglés, certificación o quieran ingresar a algún diplomado o a una universidad canadiense.',
        beca:'Cuatro semanas gratis.',
        precio:'$5,245 CAD',
        nivelIngles:'No aplica',
        razones:'Sus cursos son reconocidos en todo el mundo gracias a su gran calidad.',
        imagen: `url(${'../Imagenes/students2.jpg'})`
    },
    {
        id:3,
        programa: 'Inglés',
        pais:'Eslovaquia',
        descripcion:'Tres meses, con áreas de Negocios, Medicina y Tecnología general. Incluye: Programa y alojamiento.',
        ingreso:'Febrero 2022',
        perfil: 'Curso de inglés en Eslovaquia para personas de 18 años en adelante. Profesionales y personas que trabajan.',
        beca:'Seguro, tarjeta de transporte y dos comidas. Obtener el beneficio de no pagar matrícula al cursar el programa de nivelación en el idioma local.',
        precio:'€3,500',
        nivelIngles:'No aplica',
        razones:'Es considerado un país sin amenazas terroristas, mucho turismo y con abundante naturaleza. Los servicios no son tan costosos.',
        imagen: `url(${'../Imagenes/students1.jpg'})`
    },
    {
        id:4,
        programa: 'Inglés',
        pais:'Irlanda',
        descripcion:'Seis meses + dos meses de vacaciones, talleres para encontrar trabajo, talleres de conversación y actividades culturales.',
        ingreso:'Enero 2022',
        perfil: 'Persona que quiera mejorar su nivel de inglés, certificación o quieran ingresar a algún diplomado o universidad canadiense.',
        beca:'Inscripción, material y recepción del aeropuerto en Dublín.',
        precio:'€3,000',
        nivelIngles:'No aplica',
        razones:'Rodearse de cultura mística, paisajes, entre otros, sin mencionar que tiene muy buena calidad de vida, empleos remunerados y un sistema educativo de primera, además de ser un país estrategico para viajar a otros países.',
        imagen: `url(${'../Imagenes/students1.jpg'})`
    },
    {
        id:5,
        programa: 'Inglés',
        pais:'México',
        descripcion:'Licenciatura terminada, promedio mínimo de 8.',
        ingreso:'Enero/Diciembre',
        perfil: 'Curso de idiomas.',
        beca:'Diez meses de inglés, incluye material y alojamiento.',
        precio:'$4,800 USD',
        nivelIngles:'Intermedio',
        razones:'País rico en cultura y en oportunidades para crecer, capacidad de permitirles a los extranjeros una buena calidad de vida trabajando.',
        imagen: `url(${'../Imagenes/students5.jpg'})`
    },
    {
        id:6,
        programa: 'Inglés',
        pais:'Polonia',
        descripcion:'Diez meses de inglés en universidades (pagar registro de €750 para aplicaciones).',
        ingreso:'Enero/Septiembre',
        perfil: 'Para mejorar nivel de inglés o certificación.',
        beca:'No aplica.',
        precio:'€3,000',
        nivelIngles:'6 IELTS',
        razones:'El sistema polaco se caracteriza por su asequibilidad, accesibilidad y enfoque especializado.',
        imagen: `url(${'../Imagenes/students2.jpg'})`
    },
    {
        id:7,
        programa: 'Inglés',
        pais:'República Checa',
        descripcion:'Seis meses de inglés con preparación para IELTS, idioma chec y materias básicas.',
        ingreso:'Enero',
        perfil: 'Egresados de bachillerato que desean ingresar a la universidad para inglés intermedio.',
        beca:'Alojamiento y seguro.',
        precio:'€6,200',
        nivelIngles:'Intermedio',
        razones:'Es bastante barato a la hora de hacer compras, viajar, entre otros. El transporte público es muy completo y funciona las 24 horas. Buen promedio en desempeño en empleo, educación, relaciones sociales, seguridad y satisfacción ante la vida.',
        imagen: `url(${'../Imagenes/students3.jpg'})`
    },
    {
        id:8,
        programa: 'Inglés',
        pais:'República Checa',
        descripcion:'Un mes de alojamiento seguro.',
        ingreso:'Junio/Julio/Agosto',
        perfil: 'Curso de inglés/checo en un mes. Personas que quieran mejorar su nivel.',
        beca:'Alojamiento y seguro.',
        precio:'€2,500',
        nivelIngles:'No aplica',
        razones:'Con sus antiguos castillos, sus elegantes puentes y sus iglesias, República Checa es una ciudad que parece salida de un cuento de hadas. Praga es una ciudad bastante visible y eso se nota en su arquitectura y cultura. La ciudad de aspecto medieval es conocida por su arquitectura romántica, poblada de grandes castillos, adornadas iglesias y encantadores puentes.',
        imagen: `url(${'../Imagenes/students2.jpg'})`
    },
    {
        id:9,
        programa: 'Inglés',
        pais:'República Checa',
        descripcion:'Tres meses y alojamiento seguro.',
        ingreso:'Marzo',
        perfil: 'Curso de inglés/checo en tres meses. Personas que quieran mejorar su nivel.',
        beca:'Alojamiento y seguro.',
        precio:'€3,500',
        nivelIngles:'No aplica',
        razones:'"Con sus antiguos castillos, sus elegantes puentes y sus iglesias, República Checa es una ciudad que parece salida de un cuento de hadas. Praga es una ciudad bastante visible y eso se nota en su arquitectura y cultura. La ciudad de aspecto medieval es conocida por su arquitectura romántica, poblada de grandes castillos, adornadas iglesias y encantadores puentes.',
        imagen: `url(${'../Imagenes/students4.jpg'})`
    },
    {
        id:10,
        programa: 'Diplomado de Negocios',
        pais:'Eslovaquia',
        descripcion:'Modalidad online por tres meses y certificación europea.',
        ingreso:'Febrero 2022',
        perfil: 'Personas que estudian, quieran emprender o que tienen negocios.',
        beca:'Descuento €200 por si refiere a 3.',
        precio:'€1,200',
        nivelIngles:'No aplica',
        razones:'Se caracteriza sobre todo por sus ciudades medievales y sus iglesias de madera. También se encuentran aquí impresionantes castillos y el famoso Parque Nacional Slovensky Kras (Cárstico Eslovaco), además de sus vinos y balnearios.',
        imagen: `url(${'../Imagenes/students1.jpg'})`
    },
    {
        id:11,
        programa: 'Inglés',
        pais:'Eslovaquia',
        descripcion:'Tres meses, con áreas de Negocios, Medicina y Tecnología general. Incluye programa y alojamiento.',
        ingreso:'Febrero 2022',
        perfil: 'De 18 años en adelante, profesionales o personas que trabajan.',
        beca:'Seguro, tarjeta de transporte y dos comidas.',
        precio:'€3,500',
        nivelIngles:'No aplica',
        razones:'Se caracteriza sobre todo por sus ciudades medievales y sus iglesias de madera. También se encuentran aquí impresionantes castillos y el famoso Parque Nacional Slovensky Kras (Cárstico Eslovaco), además de sus vinos y balnearios.',
        imagen: `url(${'../Imagenes/students2.jpg'})`
    },
    {
        id:12,
        programa: 'Cursos de Verano',
        pais:'Eslovaquia',
        descripcion:'Tres semanas, programa para crear tu propio negocio online, visitar países de Europa, transporte, alojamiento y dos comidas por día.',
        ingreso:'Julio 2022',
        perfil: 'De 13 años en adelante.',
        beca:'Seguro, entradas a lugares turísticos y avión para la semana de extensión.',
        precio:'€3,800',
        nivelIngles:'No aplica',
        razones:'Se caracteriza sobre todo por sus ciudades medievales y sus iglesias de madera. También se encuentran aquí impresionantes castillos y el famoso Parque Nacional Slovensky Kras (Cárstico Eslovaco), además de sus vinos y balnearios.',
        imagen: `url(${'../Imagenes/students5.jpg'})`
    },
    {
        id:13,
        programa: 'Cursos de Verano',
        pais:'México',
        descripcion:'Crear su propio negocio y profesional para encontrar la carrera de acuerdo a su perfil.',
        ingreso:'Julio',
        perfil: 'De 13 años en adelante.',
        beca:'Incluye programa, alojamiento, dos comidas al día, visita a empresas, test vocacional y vista a lugares representantivos de México.',
        precio:'$3,000 USD',
        nivelIngles:'No aplica',
        razones:'Ofrece una amplia gama de opciones turísticas, entre las que se encuentran los destinos de playa, sitios históricos, sitios de eco-aventura, deportes extremos, recorridos culturales, entre otros.',
        imagen: `url(${'../Imagenes/students2.jpg'})`
    },
    {
        id:14,
        programa: 'Español',
        pais:'México',
        descripcion:'Por confirmar...',
        ingreso:'Por confirmar...',
        perfil: 'Por confirmar...',
        beca:'Por confirmar...',
        precio:'Por confirmar...',
        nivelIngles:'No aplica',
        razones:'Ofrece una amplia gama de opciones turísticas, entre las que se encuentran los destinos de playa, sitios históricos, sitios de eco-aventura, deportes extremos, recorridos culturales, entre otros.',
        imagen: `url(${'../Imagenes/students1.jpg'})`
    },
    {
        id:15,
        programa: 'Curso de Verano IELTS',
        pais:'República Checa',
        descripcion:'Un mes. Incluye alojamiento, seguro y material.',
        ingreso:'Julio y Agosto',
        perfil: 'Personas que quieran preparación para IELTS.',
        beca:'Alojamiento y seguro.',
        precio:'€2,500',
        nivelIngles:'No aplica',
        razones:'Es bastante barato a la hora de hacer compras, viajar, entre otros. El transporte público es muy completo y funciona las 24 horas. Buen promedio en desempeño en empleo, educación, relaciones sociales, seguridad y satisfacción ante la vida.',
        imagen: `url(${'../Imagenes/students3.jpg'})`
    },
    {
        id:16,
        programa: 'Curso de Verano IELTS',
        pais:'República Checa',
        descripcion:'Un mes. Incluye alojamiento, seguro y material.',
        ingreso:'Julio y Agosto',
        perfil: 'Personas que quieran preparación para IELTS.',
        beca:'Alojamiento y seguro.',
        precio:'€2,500',
        nivelIngles:'No aplica',
        razones:'Es bastante barato a la hora de hacer compras, viajar, entre otros. El transporte público es muy completo y funciona las 24 horas. Buen promedio en desempeño en empleo, educación, relaciones sociales, seguridad y satisfacción ante la vida.',
        imagen: `url(${'../Imagenes/students2.jpg'})`
    },
    {
        id:17,
        programa: 'Diplomado',
        pais:'República Checa',
        descripcion:'Nueve meses, uno o dos años, en áreas de Project Managment, Marketing, Tecnología, Negocios, Turismo. Servicios hospitalarios. Cuenta con permiso de trabajo.',
        ingreso:'Enero/Diciembre',
        perfil: 'Mayores de 18 años.',
        beca:'No aplica',
        precio:'$10,000 AUD',
        nivelIngles:'Intermedio',
        razones:'No aplica',
        imagen: `url(${'../Imagenes/students4.jpg'})`
    },
    {
        id:18,
        programa: 'Diplomado',
        pais:'Canadá',
        descripcion:'Desde uno a dos años, en áreas de Project Managment, Marketing, Tecnología, Negocios, Turismo. Servicios hospitalarios y niñera. Cuenta con permiso de trabajo.',
        ingreso:'Enero - Septiembre 2022',
        perfil: 'Universitarios, egresados, empleados, dueños de negocios. Promedio mínimo de 8.',
        beca:'No aplica',
        precio:'$9,700 CAD',
        nivelIngles:'Intermedio - Alto',
        razones:'No aplica',
        imagen: `url(${'../Imagenes/students5.jpg'})`
    },
    {
        id:19,
        programa: 'Licenciatura',
        pais:'Canadá',
        descripcion:'Doce meses de carrera. Puede durar hasta cuatro años si es Licenciatura y dos años si es Master.',
        ingreso:'Enero - Septiembre 2022',
        perfil: 'Egresados de bachillerato. Promedio mínimo de 8.',
        beca:'No aplica',
        precio:'$18,000 CAD',
        nivelIngles:'Intermedio - Alto',
        razones:'No aplica',
        imagen: `url(${'../Imagenes/students2.jpg'})`
    },
    {
        id:20,
        programa: 'Pregrado',
        pais:'Eslovaquia',
        descripcion:'Diez meses con idiomas inglés y eslovaco, materias básicas de la carrera, preparación y trámite para ingresar a universidades sin costo de matrícula.',
        ingreso:'Septiembre 2022',
        perfil: 'Para licenciatura, haber concluido preparatoria. Para master, haber concluido licenciatura o ingeniería. Promedio mínimo de 8.',
        beca:'Alojamiento seguro. Al concluir el curso de preparación, los cuatro años de carrera son gratis.',
        precio:'€7,800',
        nivelIngles:'Básico',
        razones:'No aplica',
        imagen: `url(${'../Imagenes/students1.jpg'})`
    },
    {
        id:21,
        programa: 'Grados',
        pais:'México',
        descripcion:'Un año de colegiatura e inscripción, con modalidad ejecutiva para estudiar y trabajar.',
        ingreso:'Enero/Mayo/Septiembre',
        perfil: 'Bachillerato concluido. Promedio mínimo de 8.',
        beca:'Alojamiento por seis meses y seguro por doce meses.',
        precio:'$7,500 USD',
        nivelIngles:'No aplica',
        razones:'No aplica',
        imagen: `url(${'../Imagenes/students3.jpg'})`
    },
    {
        id:22,
        programa: 'Master',
        pais:'México',
        descripcion:'Un año de colegiatura e inscripción, con modalidad ejecutiva para estudiar y trabajar.',
        ingreso:'Enero/Mayo/Septiembre',
        perfil: 'Licenciatura terminada. Promedio mínimo de 8.',
        beca:'Alojamiento por seis meses y seguro por doce meses.',
        precio:'$7,500 USD',
        nivelIngles:'No aplica',
        razones:'No aplica',
        imagen: `url(${'../Imagenes/students1.jpg'})`
    },
    {
        id:23,
        programa: 'Grados',
        pais:'Polonia',
        descripcion:'Carreras de cuatro años. Costo por año desde €2000. Pagar registro de €750 para aplicaciones.',
        ingreso:'Enero - Septiembre 2022',
        perfil: 'Egresados de bachillerato con promedio mínimo de 8.',
        beca:'No aplica',
        precio:'€2,000',
        nivelIngles:'IELTS 7',
        razones:'No aplica',
        imagen: `url(${'../Imagenes/students3.jpg'})`
    },
    {
        id:24,
        programa: 'Master',
        pais:'Polonia',
        descripcion:'Carreras de dos años. Costo por año desde €2000. Pagar registro de €750 para aplicaciones.',
        ingreso:'Enero - Septiembre 2022',
        perfil: 'Egresados de grado con promedio mínimo de 8.',
        beca:'No aplica',
        precio:'€2,000',
        nivelIngles:'IELTS 7',
        razones:'No aplica',
        imagen: `url(${'../Imagenes/students2.jpg'})`
    },
    {
        id:25,
        programa: 'Licenciatura',
        pais:'Reino Unido',
        descripcion:'Programa de diez meses de preparación en inglés, materias básicas, experiencia en el campus y progresión a las universidades del Rossell Group.',
        ingreso:'Enero - Septiembre 2022',
        perfil: 'Egresados de bachillerato. Promedio mínimo de 8.',
        beca:'No aplica',
        precio:'£18,000',
        nivelIngles:'Intermedio - Alto',
        razones:'No aplica',
        imagen: `url(${'../Imagenes/students5.jpg'})`
    },
    {
        id:26,
        programa: 'Foundation',
        pais:'República Checa',
        descripcion:'Diez meses. Inglés, materias básicas de la carrera, preparación y trámite para ingresar a universidades con costo de matrícula a partir de €4000 al año.',
        ingreso:'Septiembre 2022',
        perfil: 'Egresados de bachillerato o grado.',
        beca:'Alojamiento y seguro.',
        precio:'€8,700',
        nivelIngles:'Básico',
        razones:'No aplica',
        imagen: `url(${'../Imagenes/students1.jpg'})`
    },
    {
        id:27,
        programa: 'Foundation (Seis meses)',
        pais:'República Checa',
        descripcion:'Seis meses de Checo o Inglés, materias básicas de la carrera, alojamiento y seguro (si el programa es en Checo, no paga matrícula y si es en inglés, paga desde €3000 al año).',
        ingreso:'Enero',
        perfil: 'Egresados de bachillerato o grado.',
        beca:'Alojamiento y seguro.',
        precio:'€6,500',
        nivelIngles:'Básico',
        razones:'No aplica',
        imagen: `url(${'../Imagenes/students4.jpg'})`
    },
    {
        id:28,
        programa: 'Licenciatura',
        pais:'Estados Unidos',
        descripcion:'Programa de diez meses de preparación en Inglés, materias básicas de la carrera, experiencia en campus, progresión a las universidades incorporadas de Parther.',
        ingreso:'Enero - Septiembre 2022',
        perfil: 'Egresados de bachillerato y promedio mínimo de 8.',
        beca:'Descuento por universidad.',
        precio:'$18,000 USD',
        nivelIngles:'Intermedio - Alto',
        razones:'No aplica',
        imagen: `url(${'../Imagenes/students3.jpg'})`
    },
    {
        id:29,
        programa: 'Pregrado',
        pais:'Eslovaquia',
        descripcion:'Diez meses con Inglés y Eslovaco, materias básicas de la carrera, prepación y trámite para ingresar a universidades sin costo de matrícula.',
        ingreso:'Septiembre 2022',
        perfil: 'Para licenciatura, haber concluido preparatoria. Para master, haber concluido licenciatura o ingeniería. Promedio mínimo de 8.',
        beca:'Alojamiento y seguro. Al concluir el curso de preparación, los cuatro años de carrera son gratis.',
        precio:'€7,800',
        nivelIngles:'Básico',
        razones:'No aplica',
        imagen: `url(${'../Imagenes/students2.jpg'})`
    },
    {
        id:30,
        programa: 'Diplomado',
        pais:'Australia',
        descripcion:'Nueve meses, uno año o dos años, en áreas de Project Managment, Marketing, Tecnología, Negocios, Turismo. Servicios hospitalarios. Cuenta con permiso de trabajo.',
        ingreso:'Enero/Diciembre',
        perfil: 'Mayores de 18 años.',
        beca:'No aplica',
        precio:'$10,000 AUD',
        nivelIngles:'Intermedio',
        razones:'No aplica',
        imagen: `url(${'../Imagenes/students5.jpg'})`
    },
    {
        id:31,
        programa: 'Licenciatura',
        pais:'Reino Unido',
        descripcion:'Programa de diez meses de preparación en Inglés, materias básicas de la carrera, experiencia en el campus, progresion a las universidades del Rossell Group.',
        ingreso:'Enero - Septiembre 2022',
        perfil: 'Egresados de bachillerato. Promedio mínimo de 8.',
        beca:'No aplica',
        precio:'£18,000',
        nivelIngles:'Intermedio',
        razones:'No aplica',
        imagen: `url(${'../Imagenes/students2.jpg'})`
    },
    {
        id:32,
        programa: 'Licenciatura',
        pais:'Estados Unidos',
        descripcion:'Programa de diez meses de preparación en Inglés, materias básicas de la carrera, experiencia en campus, progresión a las universidades incorporadas de Parther.',
        ingreso:'Enero - Septiembre 2022',
        perfil: 'Egresados de bachillerato. Promedio mínimo de 8.',
        beca:'Descuento por universidad',
        precio:'$18,000 USD',
        nivelIngles:'Intermedio',
        razones:'No aplica',
        imagen: `url(${'../Imagenes/students2.jpg'})`
    },
    {
        id:33,
        programa: 'Diplomado',
        pais:'Canadá',
        descripcion:'Desde uno a dos años en áreas de Project Managment, Marketing, Tecnología, Negocios, Turismo. Servicios hospitalarios y niñera. Cuenta con permiso de trabajo.',
        ingreso:'Enero - Septiembre 2022',
        perfil: 'Universitarios, egresados, empleados y dueños de negocios. Promedio mínimo de 8.',
        beca:'No aplica',
        precio:'$12,000 CAD',
        nivelIngles:'Intermedio - Alto',
        razones:'No aplica',
        imagen: `url(${'../Imagenes/students1.jpg'})`
    },
    {
        id:34,
        programa: 'Licenciatura',
        pais:'Canadá',
        descripcion:'Doce meses de carrera. Puede durar hasta cuatro años si es Licenciatura y dos años si es Master.',
        ingreso:'Enero - Septiembre 2022',
        perfil: 'Egresados de bachillerato. Promedio mínimo de 8.',
        beca:'No aplica',
        precio:'$18,000 CAD',
        nivelIngles:'Intermedio - Alto',
        razones:'No aplica',
        imagen: `url(${'../Imagenes/students2.jpg'})`
    },
    {
        id:35,
        programa: 'Inglés',
        pais:'Irlanda',
        descripcion:'Seis meses y dos meses de vacaciones, talleres para encontrar trabajo, talleres de conversación y actividades culturales.',
        ingreso:'Enero 2022',
        perfil: 'Personas que quieran mejorar su nivel de Inglés, certificación o quieran ingresar a algún diplomado o universidad canadiense.',
        beca:'Inscripción, material y recepción del aeropuerto en Dublín.',
        precio:'£3,000',
        nivelIngles:'No aplica',
        razones:'No aplica',
        imagen: `url(${'../Imagenes/students2.jpg'})`
    },
    {
        id:36,
        programa: 'Grados',
        pais:'México',
        descripcion:'Un año de colegiatura, inscripción, modalidad ejecutiva.',
        ingreso:'Enero/Mayo/Septiembre',
        perfil: 'Bachillerato concluido, promedio mínimo de 8.',
        beca:'Alojamiento por seis meses y seguro por doce meses.',
        precio:'$7,500 USD',
        nivelIngles:'No aplica',
        razones:'No aplica',
        imagen: `url(${'../Imagenes/students2.jpg'})`
    },
    {
        id:37,
        programa: 'Master',
        pais:'México',
        descripcion:'Un año de colegiatura e inscripción, modalidad ejecutiva para estudiar y trabajar.',
        ingreso:'Enero/Mayo/Septiembre',
        perfil: 'Licenciatura terminada, promedio mínimo de 8.',
        beca:'Alojamiento por seis meses y seguro por doce meses.',
        precio:'$7,500 USD',
        nivelIngles:'No aplica',
        razones:'No aplica',
        imagen: `url(${'../Imagenes/students2.jpg'})`
    },
    {
        id:38,
        programa: 'Prácticas Profesionales',
        pais:'México',
        descripcion:'Taller de competencias laborales, colocación en empresas e Inglés técnico.',
        ingreso:'Enero/Mayo/Septiembre',
        perfil: 'Seis meses, para estudiantes de grado que requieren realizar sus prácticas en empresas mexicanas, generar experiencia y oportunidad laboral.',
        beca:'No aplica',
        precio:'$3,500 USD',
        nivelIngles:'No aplica',
        razones:'No aplica',
        imagen: `url(${'../Imagenes/students2.jpg'})`
    },
    {
        id:39,
        programa: 'Preuniversitario/ Premaster en Checo',
        pais:'República Checa',
        descripcion:'Diez meses, idioma checo, materias básica de la carrera, preparación y trámite para ingresar a universidades sin costo de matrícula (aplica para programas en idioma Checo).',
        ingreso:'Por confirmar...',
        perfil: 'Para licenciatura, haber concluido preparatoria. Para master, haber concluido licenciatura o ingeniería. Promedio mínimo de 8. Para cualquier área, enfocado al fútbol.',
        beca:'Alojamiento y seguro.',
        precio:'€8,500',
        nivelIngles:'Básico',
        razones:'No aplica',
        imagen: `url(${'../Imagenes/students2.jpg'})`
    },
    {
        id:40,
        programa: 'Inglés',
        pais:'República Checa',
        descripcion:'Seis meses, Inglés para prepación IELTS, idioma Checo y materias básicas de la carrera.',
        ingreso:'Enero',
        perfil: 'Egresados de bachillerato o grados que desean ingresar a la universidades.',
        beca:'Alojamiento y seguro.',
        precio:'€6,200',
        nivelIngles:'Intermedio',
        razones:'No aplica',
        imagen: `url(${'../Imagenes/students2.jpg'})`
    }
]


export default programasListado

